/**
 * ArthSetu — DPR (Detailed Project Report) PDF Generator
 *
 * Generates a structured, bankable PDF document from a FeasibilityReport.
 * Uses jsPDF for direct PDF rendering (no DOM capture needed).
 */

import jsPDF from 'jspdf';
import type { FeasibilityReport } from '@/types';
import { inr, percentage, formatDate } from '@/lib/format';

// ── Colors ──
const TEAL = [13, 78, 73] as const;    // #0D4E49
const SAFFRON = [230, 92, 0] as const;  // #E65C00
const WHITE = [255, 255, 255] as const;
const GRAY_100 = [248, 250, 252] as const;
const GRAY_300 = [203, 213, 225] as const;
const GRAY_700 = [51, 65, 85] as const;
const BLACK = [15, 23, 42] as const;

type RGB = readonly [number, number, number];

// ── Helpers ──
function setColor(doc: jsPDF, color: RGB) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function drawLine(doc: jsPDF, y: number, color: RGB = GRAY_300) {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(0.3);
  doc.line(20, y, 190, y);
}

function addPageIfNeeded(doc: jsPDF, y: number, needed = 40): number {
  if (y + needed > 270) {
    doc.addPage();
    return 20;
  }
  return y;
}

function sectionTitle(doc: jsPDF, title: string, y: number): number {
  y = addPageIfNeeded(doc, y, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  setColor(doc, TEAL);
  doc.text(title, 20, y);
  drawLine(doc, y + 2, TEAL);
  return y + 10;
}

function labelValue(doc: jsPDF, label: string, value: string, y: number, x = 20): number {
  y = addPageIfNeeded(doc, y, 8);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, GRAY_700);
  doc.text(label, x, y);
  doc.setFont('helvetica', 'bold');
  setColor(doc, BLACK);
  doc.text(value, x + 60, y);
  return y + 6;
}

// ── Main Export ──
export async function generateDPR(report: FeasibilityReport): Promise<Blob> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = 0;

  // ═══════════════════ COVER PAGE ═══════════════════
  // Background header band
  doc.setFillColor(TEAL[0], TEAL[1], TEAL[2]);
  doc.rect(0, 0, 210, 80, 'F');

  // Title
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  setColor(doc, WHITE);
  doc.text('Detailed Project Report', 105, 30, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('ArthSetu — Business Feasibility Assessment', 105, 42, { align: 'center' });

  // Saffron accent line
  doc.setFillColor(SAFFRON[0], SAFFRON[1], SAFFRON[2]);
  doc.rect(60, 52, 90, 2, 'F');

  // Business name
  doc.setFontSize(11);
  setColor(doc, [200, 230, 220]);
  doc.text(`${report.businessCategory.replace(/_/g, ' ')} Enterprise`, 105, 65, { align: 'center' });

  // Cover body
  y = 100;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  setColor(doc, TEAL);
  doc.text('Business Idea', 30, y);
  doc.setFont('helvetica', 'normal');
  setColor(doc, BLACK);
  y += 8;

  // Word-wrap business idea
  const ideaLines = doc.splitTextToSize(report.businessIdea || 'N/A', 150);
  doc.setFontSize(10);
  doc.text(ideaLines, 30, y);
  y += ideaLines.length * 5 + 10;

  // Key metrics grid
  const metrics = [
    ['Viability Score', `${report.feasibilityScore.totalScore}/100 (${report.feasibilityScore.grade})`],
    ['Project Cost', inr(report.financialPlan.projectCost)],
    ['Own Capital', inr(report.financialPlan.availableCapital)],
    ['Loan Required', inr(report.financialPlan.loanRequired)],
    ['Recommended Scheme', report.financialPlan.matchedSchemeName],
    ['Monthly EMI', inr(report.financialPlan.emi.emi)],
    ['Break-Even Month', report.financialPlan.breakEven.breakEvenMonth?.toString() ?? 'N/A'],
    ['Report Date', report.createdAt ? formatDate(report.createdAt) : new Date().toLocaleDateString('en-IN')],
  ];

  doc.setFillColor(GRAY_100[0], GRAY_100[1], GRAY_100[2]);
  doc.roundedRect(25, y - 4, 160, metrics.length * 8 + 8, 3, 3, 'F');

  for (const [label, value] of metrics) {
    y = labelValue(doc, label, value, y, 30);
  }

  // Confidence badge
  y += 8;
  doc.setFontSize(8);
  setColor(doc, GRAY_700);
  doc.text(`Confidence Level: ${report.confidence} | AI Decision: ${report.aiRecommendation.decision}`, 105, y, { align: 'center' });

  // Footer
  doc.setFontSize(7);
  setColor(doc, GRAY_300);
  doc.text('Generated by ArthSetu — Hyper-Local Enterprise Intelligence Platform', 105, 280, { align: 'center' });
  doc.text('This document can be submitted to banks as a supporting DPR for loan applications.', 105, 284, { align: 'center' });

  // ═══════════════════ PAGE 2: MARKET INTELLIGENCE ═══════════════════
  doc.addPage();
  y = 20;

  y = sectionTitle(doc, '1. Market Intelligence & Catchment Analysis', y);

  const mi = report.marketIntelligence;
  y = labelValue(doc, 'Catchment Radius', `${mi.catchmentRadiusKm} km`, y);
  y = labelValue(doc, 'Total Population', mi.totalPopulation.toLocaleString('en-IN'), y);
  y = labelValue(doc, 'Total Households', mi.totalHouseholds.toLocaleString('en-IN'), y);
  y = labelValue(doc, 'Literacy Rate', percentage(mi.literacyRate), y);

  if (mi.topCrops && mi.topCrops.length > 0) {
    const cropNames = mi.topCrops.map(c => typeof c === 'string' ? c : c.cropName).join(', ');
    y = labelValue(doc, 'Top Crops', cropNames, y);
  }

  if (mi.infrastructure) {
    const infra = mi.infrastructure as Record<string, unknown>;
    if (infra.hasAllWeatherRoad !== undefined) {
      y = labelValue(doc, 'All-Weather Road', infra.hasAllWeatherRoad ? 'Yes' : 'No', y);
    }
    if (typeof infra.nearestTownDistanceKm === 'number') {
      y = labelValue(doc, 'Nearest Town', `${infra.nearestTownDistanceKm} km`, y);
    }
  }

  y += 6;

  // ── Competition ──
  y = sectionTitle(doc, '2. Competition Analysis', y);
  const comp = report.competitorAnalysis;
  y = labelValue(doc, 'Observed Competitors', String(comp.totalObserved), y);
  y = labelValue(doc, 'Reported (Community)', String(comp.totalReported), y);
  y = labelValue(doc, 'Estimated Total', `${comp.totalEstimatedMin}–${comp.totalEstimatedMax}`, y);
  y = labelValue(doc, 'Density per sq km', comp.densityPerSqKm.toFixed(3), y);
  y = labelValue(doc, 'Data Confidence', comp.confidence, y);

  if (comp.competitors.length > 0) {
    y += 4;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, GRAY_700);
    doc.text('Known Competitors:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    for (const c of comp.competitors.slice(0, 5)) {
      y = addPageIfNeeded(doc, y, 6);
      doc.text(`• ${c.name} (${c.scale}) — ${c.distance.toFixed(1)} km away`, 25, y);
      y += 5;
    }
  }

  // ── Opportunity ──
  y += 4;
  y = sectionTitle(doc, '3. Opportunity & Market Gap Analysis', y);
  const opp = report.opportunityAnalysis;
  y = labelValue(doc, 'Opportunity Score', `${opp.opportunityScore}/100`, y);
  y = labelValue(doc, 'Recommended Model', opp.recommendedModel, y);

  if (opp.marketGaps.length > 0) {
    y += 3;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, GRAY_700);
    doc.text('Identified Market Gaps:', 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    for (const gap of opp.marketGaps.slice(0, 5)) {
      y = addPageIfNeeded(doc, y, 6);
      const lines = doc.splitTextToSize(`• ${gap}`, 160);
      doc.text(lines, 25, y);
      y += lines.length * 4.5;
    }
  }

  // ═══════════════════ PAGE 3: FINANCIAL PLAN ═══════════════════
  doc.addPage();
  y = 20;

  y = sectionTitle(doc, '4. Financial Plan & Project Cost', y);
  const fp = report.financialPlan;

  // Project cost table
  const finRows = [
    ['Total Project Cost', inr(fp.projectCost)],
    ['Own Capital (Margin)', `${inr(fp.availableCapital)} (${fp.marginPercentage}%)`],
    ['Government Subsidy', inr(fp.subsidyAmount)],
    ['Net Loan Amount', inr(fp.netLoanAmount)],
    ['Matched Scheme', fp.matchedSchemeName],
    ['Interest Rate', `${fp.interestRate}% p.a.`],
    ['Loan Tenure', `${fp.tenureMonths} months`],
    ['Monthly EMI', inr(fp.emi.emi)],
    ['Total Interest Payable', inr(fp.emi.totalInterest)],
    ['Total Repayment', inr(fp.emi.totalPayment)],
  ];

  // Draw table
  const tableX = 20;
  const colW = [85, 85];
  doc.setFillColor(TEAL[0], TEAL[1], TEAL[2]);
  doc.rect(tableX, y - 4, colW[0] + colW[1], 8, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  setColor(doc, WHITE);
  doc.text('Item', tableX + 3, y);
  doc.text('Amount', tableX + colW[0] + 3, y);
  y += 6;

  for (let i = 0; i < finRows.length; i++) {
    y = addPageIfNeeded(doc, y, 8);
    if (i % 2 === 0) {
      doc.setFillColor(GRAY_100[0], GRAY_100[1], GRAY_100[2]);
      doc.rect(tableX, y - 4, colW[0] + colW[1], 7, 'F');
    }
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    doc.text(finRows[i][0], tableX + 3, y);
    doc.setFont('helvetica', 'bold');
    doc.text(finRows[i][1], tableX + colW[0] + 3, y);
    y += 7;
  }

  // Working capital
  y += 4;
  y = labelValue(doc, 'Working Capital Required', inr(fp.workingCapital.requiredWorkingCapital), y);
  y = labelValue(doc, 'Cash Flow Status', fp.cashflow.isCashflowPositive ? 'Positive ✓' : 'Negative ✗', y);
  y = labelValue(doc, 'Break-Even Month', fp.breakEven.breakEvenMonth?.toString() ?? 'N/A', y);

  // ── Stress Test ──
  y += 6;
  y = sectionTitle(doc, '5. Stress Test & Sensitivity Analysis', y);

  const stressRows = [
    [fp.stressTest.base.name, '0%', '0%', inr(fp.stressTest.base.monthlyNetCashflow), fp.stressTest.base.canServiceDebt ? '✓' : '✗'],
    ...fp.stressTest.scenarios.map(s => [
      s.name,
      `${(s.revenueChange * 100).toFixed(0)}%`,
      `${(s.costChange * 100).toFixed(0)}%`,
      inr(s.monthlyNetCashflow),
      s.canServiceDebt ? '✓ Yes' : '✗ No',
    ]),
  ];

  // Stress test table headers
  const stressCols = [55, 25, 25, 35, 30];
  doc.setFillColor(SAFFRON[0], SAFFRON[1], SAFFRON[2]);
  doc.rect(20, y - 4, 170, 8, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  setColor(doc, WHITE);
  const stressHeaders = ['Scenario', 'Rev Δ', 'Cost Δ', 'Net CF', 'Can Pay?'];
  let sx = 22;
  for (let i = 0; i < stressHeaders.length; i++) {
    doc.text(stressHeaders[i], sx, y);
    sx += stressCols[i];
  }
  y += 6;

  for (let i = 0; i < stressRows.length; i++) {
    y = addPageIfNeeded(doc, y, 7);
    if (i % 2 === 0) {
      doc.setFillColor(GRAY_100[0], GRAY_100[1], GRAY_100[2]);
      doc.rect(20, y - 4, 170, 7, 'F');
    }
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    sx = 22;
    for (let j = 0; j < stressRows[i].length; j++) {
      doc.text(stressRows[i][j], sx, y);
      sx += stressCols[j];
    }
    y += 7;
  }

  // ═══════════════════ PAGE 4: RISK + SWOT + RECOMMENDATION ═══════════════════
  doc.addPage();
  y = 20;

  y = sectionTitle(doc, '6. Risk Assessment', y);
  const risk = report.riskAssessment;
  y = labelValue(doc, 'Overall Risk Score', `${risk.overallRiskScore}/100`, y);
  y = labelValue(doc, 'Risk Rating', risk.riskRating, y);

  y += 3;
  for (const rf of risk.riskFactors.slice(0, 5)) {
    y = addPageIfNeeded(doc, y, 16);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, GRAY_700);
    doc.text(`• ${rf.name}`, 22, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    const mitLines = doc.splitTextToSize(`Mitigation: ${rf.mitigation}`, 155);
    doc.text(mitLines, 27, y);
    y += mitLines.length * 4 + 3;
  }

  // ── SWOT ──
  y += 2;
  y = sectionTitle(doc, '7. AI SWOT Analysis', y);
  const rec = report.aiRecommendation;

  // Strengths
  y = addPageIfNeeded(doc, y, 20);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  setColor(doc, [16, 124, 65]); // green
  doc.text('Strengths:', 22, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  setColor(doc, BLACK);
  for (const s of rec.strengths.slice(0, 5)) {
    y = addPageIfNeeded(doc, y, 6);
    const lines = doc.splitTextToSize(`+ ${s}`, 155);
    doc.text(lines, 27, y);
    y += lines.length * 4.5;
  }

  // Weaknesses
  y += 3;
  y = addPageIfNeeded(doc, y, 20);
  doc.setFont('helvetica', 'bold');
  setColor(doc, [190, 50, 50]); // red
  doc.text('Weaknesses:', 22, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  setColor(doc, BLACK);
  for (const w of rec.weaknesses.slice(0, 5)) {
    y = addPageIfNeeded(doc, y, 6);
    const lines = doc.splitTextToSize(`− ${w}`, 155);
    doc.text(lines, 27, y);
    y += lines.length * 4.5;
  }

  // ── Recommendation ──
  y += 4;
  y = sectionTitle(doc, '8. AI Recommendation & Verdict', y);

  y = addPageIfNeeded(doc, y, 30);
  doc.setFillColor(GRAY_100[0], GRAY_100[1], GRAY_100[2]);
  doc.roundedRect(20, y - 4, 170, 8, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  setColor(doc, TEAL);
  doc.text(`Decision: ${rec.decision}  |  Viability: ${rec.viabilityScore}/100`, 25, y);
  y += 10;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, BLACK);
  const summaryLines = doc.splitTextToSize(rec.summary, 160);
  doc.text(summaryLines, 22, y);
  y += summaryLines.length * 4.5 + 4;

  if (rec.recommendedNextStep) {
    y = addPageIfNeeded(doc, y, 12);
    doc.setFont('helvetica', 'bold');
    setColor(doc, SAFFRON);
    doc.text('Recommended Next Step:', 22, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    const nextLines = doc.splitTextToSize(rec.recommendedNextStep, 155);
    doc.text(nextLines, 22, y);
    y += nextLines.length * 4.5;
  }

  // ═══════════════════ PAGE 5: ACTION PLAN + CHECKLIST ═══════════════════
  doc.addPage();
  y = 20;

  y = sectionTitle(doc, '9. 30-Day Action Plan', y);

  for (const milestone of report.actionPlan.milestones) {
    y = addPageIfNeeded(doc, y, 25);

    doc.setFillColor(TEAL[0], TEAL[1], TEAL[2]);
    doc.roundedRect(20, y - 4, 170, 8, 2, 2, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, WHITE);
    doc.text(`${milestone.phase} (${milestone.dayRange})`, 25, y);
    y += 7;

    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    doc.setFontSize(8.5);
    for (const task of milestone.tasks) {
      y = addPageIfNeeded(doc, y, 8);
      const taskLines = doc.splitTextToSize(`☐ ${task}`, 155);
      doc.text(taskLines, 27, y);
      y += taskLines.length * 4.5;
    }
    y += 4;
  }

  // ── Funding Readiness Checklist ──
  y += 4;
  y = sectionTitle(doc, '10. Funding Readiness Document Checklist', y);

  for (const item of report.actionPlan.fundingReadinessChecklist) {
    y = addPageIfNeeded(doc, y, 6);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, BLACK);
    doc.text(`☐  ${item}`, 25, y);
    y += 6;
  }

  // ── Matched Schemes ──
  y += 6;
  y = addPageIfNeeded(doc, y, 30);
  y = sectionTitle(doc, '11. Eligible Government Schemes', y);

  for (const scheme of report.schemeMatches.filter(s => s.eligible)) {
    y = addPageIfNeeded(doc, y, 22);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    setColor(doc, TEAL);
    doc.text(`✓ ${scheme.name}`, 22, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    setColor(doc, GRAY_700);
    doc.setFontSize(8);
    doc.text(`Max Loan: ${inr(scheme.maxLoan)} | Interest: ${scheme.interestRate}% | Subsidy: ${inr(scheme.subsidyAmount)}`, 27, y);
    y += 4;
    const reasonLines = doc.splitTextToSize(scheme.reason, 150);
    doc.text(reasonLines, 27, y);
    y += reasonLines.length * 4 + 5;
  }

  // ── Footer on every page ──
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    setColor(doc, GRAY_300);
    doc.text(`ArthSetu DPR — Page ${p} of ${totalPages}`, 105, 290, { align: 'center' });
    if (p > 1) {
      // Mini header
      doc.setFontSize(7);
      setColor(doc, GRAY_300);
      doc.text('ArthSetu — Detailed Project Report', 20, 10);
      drawLine(doc, 12, GRAY_300);
    }
  }

  return doc.output('blob');
}

/**
 * Generate and immediately download the DPR as a PDF file.
 */
export async function downloadDPR(report: FeasibilityReport): Promise<void> {
  const blob = await generateDPR(report);
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ArthSetu_DPR_${report.businessCategory}_${Date.now()}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Share via WhatsApp with a summary text.
 * On mobile, uses Web Share API to attach the PDF if available.
 * Falls back to WhatsApp deep link with text summary.
 */
export async function shareViaWhatsApp(report: FeasibilityReport): Promise<void> {
  const summary = [
    `📋 *ArthSetu Feasibility Report*`,
    ``,
    `🏪 Business: ${report.businessCategory.replace(/_/g, ' ')}`,
    `📊 Viability Score: ${report.feasibilityScore.totalScore}/100 (${report.feasibilityScore.grade})`,
    `💰 Project Cost: ${inr(report.financialPlan.projectCost)}`,
    `🏦 Loan: ${inr(report.financialPlan.netLoanAmount)} via ${report.financialPlan.matchedSchemeName}`,
    `📅 EMI: ${inr(report.financialPlan.emi.emi)}/month`,
    `✅ Decision: ${report.aiRecommendation.decision}`,
    ``,
    `Generated by ArthSetu — Rural Business Intelligence`,
  ].join('\n');

  // Try Web Share API with file (mobile)
  if (navigator.share && navigator.canShare) {
    try {
      const blob = await generateDPR(report);
      const file = new File([blob], `ArthSetu_DPR_${report.businessCategory}.pdf`, { type: 'application/pdf' });
      if (navigator.canShare({ files: [file] })) {
        await navigator.share({
          title: 'ArthSetu Feasibility Report',
          text: summary,
          files: [file],
        });
        return;
      }
    } catch {
      // Fall through to WhatsApp link
    }
  }

  // Fallback: WhatsApp deep link with text
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(summary)}`;
  window.open(whatsappUrl, '_blank');
}
