import type { FeasibilityReport } from '@/types';

export const mockReport: FeasibilityReport = {
  id: 'mock-report-001',
  businessCategory: 'DAIRY',
  businessIdea: 'Small dairy farm with 4 milch cows, selling milk and paneer locally',
  catchment: { latitude: 23.3, longitude: 87.6, radiusKm: 10 },
  marketIntelligence: {
    totalPopulation: 48200,
    totalHouseholds: 9640,
    literacyRate: 72.4,
    catchmentRadiusKm: 10,
    amenitiesCount: { schools: 18, healthCenters: 4, anganwadis: 41, banks: 3, markets: 7 },
    topCrops: ['Rice', 'Mustard', 'Potato'],
    livestock: { cattle: 12400, buffalo: 3200, goat: 5800 },
    infrastructure: {
      hasAllWeatherRoad: true,
      nearestTownDistanceKm: 8,
      mobileConnectivity: '4G',
    },
    confidence: 'HIGH',
  },
  competitorAnalysis: {
    totalObserved: 2,
    totalReported: 3,
    totalEstimatedMin: 3,
    totalEstimatedMax: 6,
    overallEstimate: 4,
    densityPerSqKm: 0.013,
    confidence: 'MEDIUM',
    competitors: [
      { name: 'Ramesh Dairy', scale: 'MICRO', distance: 3.2 },
      { name: 'Sunita Milk Parlour', scale: 'MICRO', distance: 4.8 },
    ],
  },
  opportunityAnalysis: {
    marketGaps: [
      'No organized paneer supplier within 5km',
      'Anganwadi supply contracts unfilled',
      'Home delivery not offered by existing players',
    ],
    potentialNiches: ['Paneer / curd production', 'Institutional supply (anganwadis, schools)', 'Home delivery route'],
    recommendedModel: 'Mixed dairy: fresh milk + value-added paneer/curd',
    opportunityScore: 74,
    estimatedAnnualDemandUnits: 87600,
    estimatedDailyDemandUnits: 240,
    unit: 'litres',
    keyDrivers: ['High cattle population signals dairy culture', 'Underserved paneer market', '41 anganwadis as institutional buyers'],
  },
  financialPlan: {
    projectCost: 185000,
    availableCapital: 50000,
    loanRequired: 135000,
    marginPercentage: 27,
    matchedSchemeName: 'MUDRA Kishore',
    interestRate: 10.5,
    tenureMonths: 36,
    subsidyAmount: 15000,
    netLoanAmount: 120000,
    emi: {
      emi: 3847,
      totalInterest: 18492,
      totalPayment: 138492,
      schedule: Array.from({ length: 36 }, (_, i) => ({
        month: i + 1,
        principal: 3333,
        interest: Math.max(100, 514 - i * 14),
        balance: Math.max(0, 120000 - (i + 1) * 3333),
      })),
    },
    workingCapital: {
      requiredWorkingCapital: 24600,
      monthsCovered: 3,
    },
    cashflow: {
      projections: Array.from({ length: 12 }, (_, i) => ({
        month: i + 1,
        revenue: i === 7 ? 9800 : 14500,
        operatingCosts: 8200,
        emi: 3847,
        netCashflow: i === 7 ? 9800 - 8200 - 3847 : 14500 - 8200 - 3847,
        cumulativeCashflow: (i + 1) * 2453 - (i === 7 ? 4906 : 0),
      })),
      averageMonthlyCashflow: 2200,
      isCashflowPositive: true,
    },
    breakEven: {
      breakEvenUnits: 820,
      breakEvenRevenue: 12300,
      breakEvenMonth: 2,
      isViable: true,
      chartData: Array.from({ length: 12 }, (_, i) => ({
        month: i + 1,
        revenue: 14500 * (i + 1),
        totalCost: 185000 + 8200 * (i + 1) + 3847 * (i + 1),
      })),
    },
    stressTest: {
      base: {
        name: 'Base Case',
        revenueChange: 0,
        costChange: 0,
        monthlyNetCashflow: 2453,
        canServiceDebt: true,
      },
      scenarios: [
        { name: '+15% raw material cost', revenueChange: 0, costChange: 0.15, monthlyNetCashflow: 1223, canServiceDebt: true },
        { name: '-20% demand', revenueChange: -0.2, costChange: 0, monthlyNetCashflow: 553, canServiceDebt: true },
        { name: 'Drought (-30% revenue)', revenueChange: -0.3, costChange: 0.15, monthlyNetCashflow: -3127, canServiceDebt: false },
      ],
    },
  },
  schemeMatches: [
    {
      id: 'scheme-mudra-kishore',
      name: 'MUDRA Kishore',
      description: 'Micro Units Development & Refinance Agency — Kishore category for enterprises needing ₹50K–₹5L',
      maxLoan: 500000,
      interestRate: 10.5,
      tenureMonths: 36,
      moratoriumMonths: 3,
      subsidyAmount: 15000,
      netLoanAmount: 120000,
      eligible: true,
      reason: 'Matches: OBC category, dairy sector, project cost ₹1.85L within limit',
    },
    {
      id: 'scheme-pmegp-dairy',
      name: 'PMEGP — Dairy & Animal Husbandry',
      description: 'Prime Minister Employment Generation Programme for dairy and animal husbandry enterprises',
      maxLoan: 2500000,
      interestRate: 11.0,
      tenureMonths: 60,
      moratoriumMonths: 6,
      subsidyAmount: 37500,
      netLoanAmount: 97500,
      eligible: true,
      reason: 'Matches: OBC category, dairy sector, project cost ₹1.85L within limit',
    },
    {
      id: 'scheme-nabard-dairy',
      name: 'NABARD Dairy Entrepreneurship Development',
      description: 'National Bank for Agriculture — Dairy Entrepreneurship Development Scheme (DEDS)',
      maxLoan: 700000,
      interestRate: 8.75,
      tenureMonths: 48,
      moratoriumMonths: 3,
      subsidyAmount: 25000,
      netLoanAmount: 110000,
      eligible: false,
      reason: 'Not eligible: minimum 10 milch animals required; current plan has 4',
    },
  ],
  riskAssessment: {
    riskFactors: [
      { name: 'Seasonal demand fluctuation', probability: 0.7, impact: 0.5, mitigation: 'Diversify into paneer/curd during low-milk months; build institutional buyer relationships with anganwadis for stable off-take.' },
      { name: 'Cattle disease / mortality', probability: 0.3, impact: 0.8, mitigation: 'Enroll in Pradhan Mantri Fasal Bima Yojana livestock insurance; maintain minimum 2-month working capital buffer.' },
      { name: 'Feed cost inflation', probability: 0.6, impact: 0.4, mitigation: 'Grow 20% of fodder on available land; lock in monthly contracts with local feed suppliers.' },
      { name: 'New competitor entry', probability: 0.4, impact: 0.5, mitigation: 'Build brand loyalty through home delivery and consistent quality; register under FSSAI for credibility.' },
      { name: 'Delayed loan disbursement', probability: 0.35, impact: 0.6, mitigation: 'Apply to 2 schemes simultaneously; begin with smaller scale using own capital while loan processes.' },
    ],
    overallRiskScore: 42,
    riskRating: 'MEDIUM',
  },
  feasibilityScore: {
    marketDemandScore: 16,
    competitionScore: 14,
    financialViabilityScore: 15,
    capitalAdequacyScore: 13,
    riskResilienceScore: 14,
    totalScore: 72,
    grade: 'GOOD',
  },
  actionPlan: {
    planDurationDays: 30,
    milestones: [
      {
        phase: 'Foundation',
        dayRange: 'Day 1–7',
        tasks: [
          'Open a dedicated business savings account (SBI / Bank of Baroda)',
          'Collect Aadhaar, PAN, caste certificate, land documents',
          'Visit nearest MUDRA-empanelled bank branch with documents',
          'Register on Udyam portal (udyamregistration.gov.in) — free, 10 minutes',
        ],
      },
      {
        phase: 'Scheme Application',
        dayRange: 'Day 8–15',
        tasks: [
          'Submit MUDRA Kishore loan application with DPR (use this report as supporting document)',
          'Apply for PMEGP simultaneously through nearest KVIC/DIC office',
          'Get cattle insurance quote from nearest insurance agent',
          'Identify and shortlist 2 local cattle suppliers — visit in person',
        ],
      },
      {
        phase: 'Setup & Procurement',
        dayRange: 'Day 16–25',
        tasks: [
          'Purchase 4 milch cows from verified supplier (negotiate 15-day health guarantee)',
          'Set up shed: ventilation, drainage, milking area (use available land)',
          'Purchase milking equipment, storage cans, chilling equipment',
          'Register with local milk cooperative or direct buyer — get supply agreement in writing',
        ],
      },
      {
        phase: 'Launch',
        dayRange: 'Day 26–30',
        tasks: [
          'Begin morning milk collection and delivery route',
          'Deliver samples to 3 local sweet shops for paneer supply negotiation',
          'Apply to 5 nearest anganwadis for bulk milk supply contract',
          'Set up UPI QR code for digital payments — display prominently',
        ],
      },
    ],
    fundingReadinessChecklist: [
      'Aadhaar card (self + spouse)',
      'PAN card',
      'Caste / Category certificate (SC/ST/OBC)',
      'Residence proof (electricity bill / ration card)',
      'Bank account passbook (last 6 months statement)',
      'Land ownership / lease document',
      'Passport-size photographs (6 copies)',
      'Business plan / DPR (this report qualifies)',
      'Quotations for cattle purchase (2 suppliers)',
      'Quotations for equipment (milking machine, cans)',
      'FSSAI registration (basic, free)',
      'Udyam registration certificate',
    ],
  },
  aiRecommendation: {
    decision: 'PROCEED',
    viabilityScore: 72,
    summary: 'The dairy business in Bishnupur block shows strong fundamentals: high local cattle population, an underserved paneer market, and 41 anganwadis as potential institutional buyers. The MUDRA Kishore scheme matches well and the EMI of ₹3,847 is comfortably covered by projected monthly net cashflow of ₹7,563. The primary risk is seasonal demand — mitigated by diversifying into paneer/curd production.',
    strengths: [
      'No organized dairy competitor within 5km radius',
      'High catchment cattle population (12,400) signals established dairy culture',
      'Monthly cashflow positive from Month 1',
      'MUDRA Kishore scheme available with ₹15,000 subsidy',
      '4G connectivity enables digital payments and home-delivery coordination',
    ],
    weaknesses: [
      'Capital adequacy is moderate — only 27% own contribution',
      'Drought scenario (-30% revenue) makes EMI unserviceable',
      'No cold-chain infrastructure in catchment — limits paneer shelf life',
      'Seasonal demand dip in Month 8 requires working capital buffer',
    ],
    recommendedNextStep: 'Apply for MUDRA Kishore loan at nearest SBI/BoB branch. Carry this report, Aadhaar, PAN, and caste certificate. Simultaneously register on Udyam portal (free, 10 minutes) to unlock scheme eligibility.',
  },
  status: 'COMPLETED',
  confidence: 'HIGH',
  createdAt: '2026-09-06T05:24:45.988Z',
};
const MOCK_REPORT: unknown = null;

export { MOCK_REPORT };