import type { FeasibilityReport } from '@/types';

export const mockReport: FeasibilityReport = {
  id: 'mock-report-001',
  businessCategory: 'DAIRY',
  businessIdea: 'Small dairy farm with 4 milch cows, selling milk and paneer locally',
  catchment: { latitude: 23.3, longitude: 87.6, radiusKm: 10 },
  marketIntelligence: {
    totalPopulation: 48200,
    totalHouseholds: 9640,
    literacyRate: 72.4,
    catchmentRadiusKm: 10,
    amenitiesCount: { schools: 18, healthCenters: 4, anganwadis: 41, banks: 3, markets: 7 },
    topCrops: ['Rice', 'Mustard', 'Potato'],
    livestock: { cattle: 12400, buffalo: 3200, goat: 5800 },
    infrastructure: {
      hasAllWeatherRoad: true,
      nearestTownDistanceKm: 8,
      mobileConnectivity: '4G',
    },
    confidence: 'HIGH',
  },
  competitorAnalysis: {
    totalObserved: 2,
    totalReported: 3,
    totalEstimatedMin: 3,
    totalEstimatedMax: 6,
    overallEstimate: 4,
    densityPerSqKm: 0.013,
    confidence: 'MEDIUM',
    competitors: [
      { name: 'Ramesh Dairy', scale: 'MICRO', distance: 3.2 },
      { name: 'Sunita Milk Parlour', scale: 'MICRO', distance: 4.8 },
    ],
  },
  opportunityAnalysis: {
    marketGaps: [
      'No organized paneer supplier within 5km',
      'Anganwadi supply contracts unfilled',
      'Home delivery not offered by existing players',
    ],
    potentialNiches: ['Paneer / curd production', 'Institutional supply (anganwadis, schools)', 'Home delivery route'],
    recommendedModel: 'Mixed dairy: fresh milk + value-added paneer/curd',
    opportunityScore: 74,
    estimatedAnnualDemandUnits: 87600,
    estimatedDailyDemandUnits: 240,
    unit: 'litres',
    keyDrivers: ['High cattle population signals dairy culture', 'Underserved paneer market', '41 anganwadis as institutional buyers'],
  },
  financialPlan: {
    projectCost: 185000,
    availableCapital: 50000,
    loanRequired: 135000,
    marginPercentage: 27,
    matchedSchemeName: 'MUDRA Kishore',
    interestRate: 10.5,
    tenureMonths: 36,
    subsidyAmount: 15000,
    netLoanAmount: 120000,
    emi: {
      emi: 3847,
      totalInterest: 18492,
      totalPayment: 138492,
      schedule: Array.from({ length: 36 }, (_, i) => ({
        month: i + 1,
        principal: 3333,
        interest: Math.max(100, 514 - i * 14),
        balance: Math.max(0, 120000 - (i + 1) * 3333),
      })),
    },
    workingCapital: {
      requiredWorkingCapital: 24600,
      monthsCovered: 3,
      inventoryDays: 15,
      receivableDays: 15,
      payableDays: 10,
      operatingCycleDays: 20,
      dailyExpense: 273.33,
      baseWorkingCapital: 5466.67,
      bufferAmount: 546.67,
    },
    dscr: {
      dscr: 1.64,
      status: 'EXCELLENT',
      benchmarkText: 'DSCR is 1.64 (> 1.50). High debt service capacity; highly acceptable to banks and NABARD.',
    },
    assumptions: {
      revenueItems: [
        {
          name: 'Fresh Cow Milk Sales',
          dailyUnits: 30,
          unitPrice: 45,
          unitName: 'litres',
          dailyRevenue: 1350,
          monthlyRevenue: 40500,
        },
        {
          name: 'Fresh Paneer / Cottage Cheese',
          dailyUnits: 3,
          unitPrice: 320,
          unitName: 'kg',
          dailyRevenue: 960,
          monthlyRevenue: 28800,
        },
        {
          name: 'Organic Cow Dung Manure',
          dailyUnits: 2,
          unitPrice: 150,
          unitName: 'bags',
          dailyRevenue: 300,
          monthlyRevenue: 9000,
        },
      ],
      costItems: [
        {
          category: 'Cattle Feed & Fodder (Green & Dry)',
          monthlyAmount: 22500,
          description: '35 kg fodder + 12 kg cattle feed concentrate daily for 4 milch cows',
          isDirectCost: true,
        },
        {
          category: 'Veterinary Care & Vaccines',
          monthlyAmount: 2500,
          description: 'Regular checkups, artificial insemination, and deworming per month',
          isDirectCost: true,
        },
        {
          category: 'Helpers & Farm Labor (Part-time)',
          monthlyAmount: 7000,
          description: '1 part-time milking assistant for morning & evening shift',
          isDirectCost: false,
        },
        {
          category: 'Shed Utilities & Water Supply',
          monthlyAmount: 2200,
          description: 'Electricity for chilling unit, water pumping, shed lighting',
          isDirectCost: false,
        },
        {
          category: 'Packaging & Delivery Fuel',
          monthlyAmount: 3800,
          description: 'Milk cans, bio-degradable paneer pouches, e-rickshaw charging / fuel',
          isDirectCost: false,
        },
      ],
      methodologyNotes: [
        'Revenue derived from 4 high-yield crossbred cows producing an average of 10-12 litres/day each.',
        'Milk pricing is set at local West Bengal rural mandi rate (₹45/litre for 4.5% fat milk).',
        '20% of milk is converted into value-added paneer (conversion yield: 10L milk → 1.8 kg paneer + whey).',
        'Operating costs benchmarked using NDDB (National Dairy Development Board) smallholder guidelines.',
      ],
    },
    seasonalMultipliers: [
      { monthIndex: 0, monthName: 'Jan', multiplier: 1.15, status: 'PEAK', reason: 'High milk yield in winter; peak festival sweet demand (Poush Sankranti)' },
      { monthIndex: 1, monthName: 'Feb', multiplier: 1.10, status: 'PEAK', reason: 'Favorable climate; high marriage season sweet demand' },
      { monthIndex: 2, monthName: 'Mar', multiplier: 1.00, status: 'NORMAL', reason: 'Moderate demand and steady milk yield' },
      { monthIndex: 3, monthName: 'Apr', multiplier: 0.95, status: 'NORMAL', reason: 'Summer onset; slight drop in lactation yield' },
      { monthIndex: 4, monthName: 'May', multiplier: 0.88, status: 'LEAN', reason: 'Peak summer heat; lower milk yield due to heat stress in cattle' },
      { monthIndex: 5, monthName: 'Jun', multiplier: 0.82, status: 'LEAN', reason: 'Monsoon onset & humidity; lean lactation period' },
      { monthIndex: 6, monthName: 'Jul', multiplier: 0.85, status: 'LEAN', reason: 'Green fodder availability improves yield slightly' },
      { monthIndex: 7, monthName: 'Aug', multiplier: 0.95, status: 'NORMAL', reason: 'Festival season starts (Janmashtami, Raksha Bandhan)' },
      { monthIndex: 8, monthName: 'Sep', multiplier: 1.05, status: 'NORMAL', reason: 'Preparation for Durga Puja sweet making' },
      { monthIndex: 9, monthName: 'Oct', multiplier: 1.25, status: 'PEAK', reason: 'Durga Puja & Laxmi Puja peak sweet consumption' },
      { monthIndex: 10, monthName: 'Nov', multiplier: 1.20, status: 'PEAK', reason: 'Kali Puja, Diwali & winter marriage season' },
      { monthIndex: 11, monthName: 'Dec', multiplier: 1.15, status: 'PEAK', reason: 'Winter picnic season & high dairy fat yield' },
    ],
    cashflow: {
      projections: Array.from({ length: 12 }, (_, i) => {
        const season = [1.15, 1.10, 1.00, 0.95, 0.88, 0.82, 0.85, 0.95, 1.05, 1.25, 1.20, 1.15][i];
        const rev = Math.round(78300 * season);
        const ops = 38000;
        const emi = 3847;
        const net = rev - ops - emi;
        return {
          month: i + 1,
          revenue: rev,
          operatingCosts: ops,
          emi: emi,
          netCashflow: net,
          cumulativeCashflow: Math.round((i + 1) * 36453 * season),
        };
      }),
      averageMonthlyCashflow: 36453,
      isCashflowPositive: true,
    },
    breakEven: {
      breakEvenUnits: 820,
      breakEvenRevenue: 38000,
      breakEvenMonth: 4,
      isViable: true,
      chartData: Array.from({ length: 12 }, (_, i) => ({
        month: i + 1,
        revenue: 78300 * (i + 1),
        totalCost: 185000 + 38000 * (i + 1) + 3847 * (i + 1),
      })),
    },
    stressTest: {
      base: {
        name: 'Base Case',
        revenueChange: 0,
        costChange: 0,
        monthlyNetCashflow: 36453,
        canServiceDebt: true,
      },
      scenarios: [
        { name: '+15% raw material cost', revenueChange: 0, costChange: 0.15, monthlyNetCashflow: 30753, canServiceDebt: true },
        { name: '-20% demand', revenueChange: -0.2, costChange: 0, monthlyNetCashflow: 20793, canServiceDebt: true },
        { name: 'Drought (-30% revenue)', revenueChange: -0.3, costChange: 0.15, monthlyNetCashflow: 7243, canServiceDebt: true },
      ],
    },
    equipmentList: [
      {
        id: 'eq-001',
        name: 'High-Yield Milch Cows (Crossbred Jersey / Holstein)',
        category: 'MACHINERY',
        estimatedCost: 120000,
        quantity: 4,
        unit: 'animals',
        importance: 'ESSENTIAL',
        specification: '2nd/3rd lactation cows yielding 12–14 litres/day with medical & vaccination certificate',
        vendorType: 'Verified Cattle Breeder / Local Livestock Haat',
      },
      {
        id: 'eq-002',
        name: 'Stainless Steel Milk Cans (Food Grade SS 304)',
        category: 'INSTRUMENT',
        estimatedCost: 6500,
        quantity: 2,
        unit: 'cans (40L)',
        importance: 'ESSENTIAL',
        specification: 'Food-grade SS 304 seamless body with airtight cover & heavy-duty handles',
        vendorType: 'Authorized Dairy Equipment Dealer / Local Market',
      },
      {
        id: 'eq-003',
        name: 'Automatic Double-Bucket Milking Machine',
        category: 'MACHINERY',
        estimatedCost: 18500,
        quantity: 1,
        unit: 'unit',
        importance: 'ESSENTIAL',
        specification: 'Single-phase 1HP vacuum pump motor, pulsator 60/40, food-grade silicone teat cups',
        vendorType: 'Empanelled Agro-Machinery Distributor / KVIC Vendor',
      },
      {
        id: 'eq-004',
        name: 'Direct Expansion Bulk Milk Chilling Unit (100L)',
        category: 'MACHINERY',
        estimatedCost: 25000,
        quantity: 1,
        unit: 'unit',
        importance: 'RECOMMENDED',
        specification: 'Chills raw milk from 35°C to 4°C within 2 hours; auto digital temperature controller',
        vendorType: 'Cooperative Dairy Supplier / Cold Chain Vendor',
      },
      {
        id: 'eq-005',
        name: 'Digital Ultrasonic Milk Fat & SNF Tester',
        category: 'INSTRUMENT',
        estimatedCost: 4200,
        quantity: 1,
        unit: 'device',
        importance: 'RECOMMENDED',
        specification: 'Tests Fat (0.01%–12%) & SNF (3%–15%) in 60s with 12V DC battery backup',
        vendorType: 'Dairy Testing Equipment Supplier',
      },
      {
        id: 'eq-006',
        name: 'Electric Chaff Cutter / Green Fodder Chopper',
        category: 'MACHINERY',
        estimatedCost: 10800,
        quantity: 1,
        unit: 'machine',
        importance: 'ESSENTIAL',
        specification: '2HP single-phase motor, 500 kg/hr processing capacity, alloy steel blades',
        vendorType: 'Local Agro Implement Dealer / Hardware Market',
      },
    ],
  },
  equipmentList: [
    {
      id: 'eq-001',
      name: 'High-Yield Milch Cows (Crossbred Jersey / Holstein)',
      category: 'MACHINERY',
      estimatedCost: 120000,
      quantity: 4,
      unit: 'animals',
      importance: 'ESSENTIAL',
      specification: '2nd/3rd lactation cows yielding 12–14 litres/day with medical & vaccination certificate',
      vendorType: 'Verified Cattle Breeder / Local Livestock Haat',
    },
    {
      id: 'eq-002',
      name: 'Stainless Steel Milk Cans (Food Grade SS 304)',
      category: 'INSTRUMENT',
      estimatedCost: 6500,
      quantity: 2,
      unit: 'cans (40L)',
      importance: 'ESSENTIAL',
      specification: 'Food-grade SS 304 seamless body with airtight cover & heavy-duty handles',
      vendorType: 'Authorized Dairy Equipment Dealer / Local Market',
    },
    {
      id: 'eq-003',
      name: 'Automatic Double-Bucket Milking Machine',
      category: 'MACHINERY',
      estimatedCost: 18500,
      quantity: 1,
      unit: 'unit',
      importance: 'ESSENTIAL',
      specification: 'Single-phase 1HP vacuum pump motor, pulsator 60/40, food-grade silicone teat cups',
      vendorType: 'Empanelled Agro-Machinery Distributor / KVIC Vendor',
    },
    {
      id: 'eq-004',
      name: 'Direct Expansion Bulk Milk Chilling Unit (100L)',
      category: 'MACHINERY',
      estimatedCost: 25000,
      quantity: 1,
      unit: 'unit',
      importance: 'RECOMMENDED',
      specification: 'Chills raw milk from 35°C to 4°C within 2 hours; auto digital temperature controller',
      vendorType: 'Cooperative Dairy Supplier / Cold Chain Vendor',
    },
    {
      id: 'eq-005',
      name: 'Digital Ultrasonic Milk Fat & SNF Tester',
      category: 'INSTRUMENT',
      estimatedCost: 4200,
      quantity: 1,
      unit: 'device',
      importance: 'RECOMMENDED',
      specification: 'Tests Fat (0.01%–12%) & SNF (3%–15%) in 60s with 12V DC battery backup',
      vendorType: 'Dairy Testing Equipment Supplier',
    },
    {
      id: 'eq-006',
      name: 'Electric Chaff Cutter / Green Fodder Chopper',
      category: 'MACHINERY',
      estimatedCost: 10800,
      quantity: 1,
      unit: 'machine',
      importance: 'ESSENTIAL',
      specification: '2HP single-phase motor, 500 kg/hr processing capacity, alloy steel blades',
      vendorType: 'Local Agro Implement Dealer / Hardware Market',
    },
  ],
  schemeMatches: [
    {
      id: 'scheme-mudra-kishore',
      name: 'MUDRA Kishore',
      description: 'Micro Units Development & Refinance Agency — Kishore category for enterprises needing ₹50K–₹5L',
      maxLoan: 500000,
      interestRate: 10.5,
      tenureMonths: 36,
      moratoriumMonths: 3,
      subsidyAmount: 15000,
      netLoanAmount: 120000,
      eligible: true,
      reason: 'Matches: OBC category, dairy sector, project cost ₹1.85L within limit',
    },
    {
      id: 'scheme-pmegp-dairy',
      name: 'PMEGP — Dairy & Animal Husbandry',
      description: 'Prime Minister Employment Generation Programme for dairy and animal husbandry enterprises',
      maxLoan: 2500000,
      interestRate: 11.0,
      tenureMonths: 60,
      moratoriumMonths: 6,
      subsidyAmount: 37500,
      netLoanAmount: 97500,
      eligible: true,
      reason: 'Matches: OBC category, dairy sector, project cost ₹1.85L within limit',
    },
    {
      id: 'scheme-nabard-dairy',
      name: 'NABARD Dairy Entrepreneurship Development',
      description: 'National Bank for Agriculture — Dairy Entrepreneurship Development Scheme (DEDS)',
      maxLoan: 700000,
      interestRate: 8.75,
      tenureMonths: 48,
      moratoriumMonths: 3,
      subsidyAmount: 25000,
      netLoanAmount: 110000,
      eligible: false,
      reason: 'Not eligible: minimum 10 milch animals required; current plan has 4',
    },
  ],
  riskAssessment: {
    riskFactors: [
      { name: 'Seasonal demand fluctuation', probability: 0.7, impact: 0.5, mitigation: 'Diversify into paneer/curd during low-milk months; build institutional buyer relationships with anganwadis for stable off-take.' },
      { name: 'Cattle disease / mortality', probability: 0.3, impact: 0.8, mitigation: 'Enroll in Pradhan Mantri Fasal Bima Yojana livestock insurance; maintain minimum 2-month working capital buffer.' },
      { name: 'Feed cost inflation', probability: 0.6, impact: 0.4, mitigation: 'Grow 20% of fodder on available land; lock in monthly contracts with local feed suppliers.' },
      { name: 'New competitor entry', probability: 0.4, impact: 0.5, mitigation: 'Build brand loyalty through home delivery and consistent quality; register under FSSAI for credibility.' },
      { name: 'Delayed loan disbursement', probability: 0.35, impact: 0.6, mitigation: 'Apply to 2 schemes simultaneously; begin with smaller scale using own capital while loan processes.' },
    ],
    overallRiskScore: 42,
    riskRating: 'MEDIUM',
  },
  feasibilityScore: {
    marketDemandScore: 16,
    competitionScore: 14,
    financialViabilityScore: 15,
    capitalAdequacyScore: 13,
    riskResilienceScore: 14,
    totalScore: 72,
    grade: 'GOOD',
  },
  actionPlan: {
    planDurationDays: 30,
    milestones: [
      {
        phase: 'Foundation',
        dayRange: 'Day 1–7',
        tasks: [
          'Open a dedicated business savings account (SBI / Bank of Baroda)',
          'Collect Aadhaar, PAN, caste certificate, land documents',
          'Visit nearest MUDRA-empanelled bank branch with documents',
          'Register on Udyam portal (udyamregistration.gov.in) — free, 10 minutes',
        ],
      },
      {
        phase: 'Scheme Application',
        dayRange: 'Day 8–15',
        tasks: [
          'Submit MUDRA Kishore loan application with DPR (use this report as supporting document)',
          'Apply for PMEGP simultaneously through nearest KVIC/DIC office',
          'Get cattle insurance quote from nearest insurance agent',
          'Identify and shortlist 2 local cattle suppliers — visit in person',
        ],
      },
      {
        phase: 'Setup & Procurement',
        dayRange: 'Day 16–25',
        tasks: [
          'Purchase 4 milch cows from verified supplier (negotiate 15-day health guarantee)',
          'Set up shed: ventilation, drainage, milking area (use available land)',
          'Purchase milking equipment, storage cans, chilling equipment',
          'Register with local milk cooperative or direct buyer — get supply agreement in writing',
        ],
      },
      {
        phase: 'Launch',
        dayRange: 'Day 26–30',
        tasks: [
          'Begin morning milk collection and delivery route',
          'Deliver samples to 3 local sweet shops for paneer supply negotiation',
          'Apply to 5 nearest anganwadis for bulk milk supply contract',
          'Set up UPI QR code for digital payments — display prominently',
        ],
      },
    ],
    fundingReadinessChecklist: [
      'Aadhaar card (self + spouse)',
      'PAN card',
      'Caste / Category certificate (SC/ST/OBC)',
      'Residence proof (electricity bill / ration card)',
      'Bank account passbook (last 6 months statement)',
      'Land ownership / lease document',
      'Passport-size photographs (6 copies)',
      'Business plan / DPR (this report qualifies)',
      'Quotations for cattle purchase (2 suppliers)',
      'Quotations for equipment (milking machine, cans)',
      'FSSAI registration (basic, free)',
      'Udyam registration certificate',
    ],
  },
  aiRecommendation: {
    decision: 'PROCEED',
    viabilityScore: 72,
    summary: 'The dairy business in Bishnupur block shows strong fundamentals: high local cattle population, an underserved paneer market, and 41 anganwadis as potential institutional buyers. The MUDRA Kishore scheme matches well and the EMI of ₹3,847 is comfortably covered by projected monthly net cashflow of ₹7,563. The primary risk is seasonal demand — mitigated by diversifying into paneer/curd production.',
    strengths: [
      'No organized dairy competitor within 5km radius',
      'High catchment cattle population (12,400) signals established dairy culture',
      'Monthly cashflow positive from Month 1',
      'MUDRA Kishore scheme available with ₹15,000 subsidy',
      '4G connectivity enables digital payments and home-delivery coordination',
    ],
    weaknesses: [
      'Capital adequacy is moderate — only 27% own contribution',
      'Drought scenario (-30% revenue) makes EMI unserviceable',
      'No cold-chain infrastructure in catchment — limits paneer shelf life',
      'Seasonal demand dip in Month 8 requires working capital buffer',
    ],
    recommendedNextStep: 'Apply for MUDRA Kishore loan at nearest SBI/BoB branch. Carry this report, Aadhaar, PAN, and caste certificate. Simultaneously register on Udyam portal (free, 10 minutes) to unlock scheme eligibility.',
  },
  status: 'COMPLETED',
  confidence: 'HIGH',
  createdAt: '2026-09-06T05:24:45.988Z',
};
const MOCK_REPORT: unknown = null;

export { MOCK_REPORT };